### ISSUE TITLE
有一些用户的微博图片上面不显示1，2，3... 和all怎么办啊？主页也是有时显示有时不显示

### ISSUE THREAD

**Issue by doio** [adelabs/user.js#1]
我装了：
新浪微博之我要看大图
Yet Another Weibo Filter
可是禁用这两个以后，
Weibo Big Picture还是在有的页面无效，有时有有时没呀....

**Comment by tiansh** [comment]
目测是图片的识别有问题，这样改一下应该就好了。

``` patch
49,50c49,51
<         $(list).find('img[node-type="fl_media_bgimg"], ' +  // single pic
<                      'img[action-type="fl_pics"]'           // multiple pic
---
>         $(list).find('img[node-type="feed_list_media_bgimg"], ' + // single pic
>                      'img[node-type="fl_media_bgimg"], ' +        // single pic
>                      'img[action-type="fl_pics"]'                 // multiple pic
```

**Comment by doio** [comment]
谢谢作者！！！这样似乎没问题了！！！XDXD

**Comment by tiansh** [comment]
我不是作者……

19.01.2016, 20:05, "Avioza" notifications@github.com:

**Comment by doio** [comment]
啊哈哈哈管它黑作者白作者，修正插件的作者都是好作者！！！
对了，（）作者，我还发现了，问题貌似解决了，可是还是有很大的几率在第一次载入页面的时候，1,2,3...All 这些不会显示，要重新刷新页面才会有，又是什么问题呢？其他类似的插件，例如上述说的新浪微博之我要看大图，就没有这种情况...

**Comment by adelabs** [comment]
一般是第一次刷新都能正常工作的，但点“下一页“之后重新刷出来的就有问题了。不知道怎么监控事件。

**Comment by tiansh** [comment]
@adelabs

可以用 [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) 暴力解决……

**Comment by adelabs** [comment]
fixed in a stupid way
