### ISSUE TITLE
求适配新版微博页面

### ISSUE THREAD

**Issue by doio** [adelabs/user.js#2]
201603024更新了新版页面以后插件失效！！！
求适配！！
我自己想改，但是实在找不到思路.....

求老司机带路！！！

**Comment by adelabs** [comment]
Updated

**Comment by dQmZ46pKrwv53DB** [comment]
> 201603024更新了新版页面以后插件失效！！！ 求适配！！ 我自己想改，但是实在找不到思路.....
> 
> 求老司机带路！！！
